import java.util.Scanner;

public class P121
{
  public static void main(String[] args)
  {
    Scanner sc= new Scanner(System.in);
	int attempt;
	int rand = (int)(Math.random() * 20) + 1;
	System.out.print("Guess the number generated by the computer (1-20): ");
	attempt= sc.nextInt();
	if (rand==attempt)
		{
			System.out.println("Congrats! You got it!");
		}else
			{
				System.out.println("You failed, scrub. The right number was " + rand);
			}
  }
}
